lib/Controllers/base.js, lib/Controllers/create.js, lib/Controllers/delete.js, lib/Controllers/list.js, lib/Resource.js, package.json, tests/milestones/milestones.test.js, tests/resource/resource.test.js
Added a few missing tests, and removed a number of questionable code
sections which were never run (or could never possibly be run). The
result is 100% test coverage for the the project.
Of note is:
* the removal of endpoint attribute addition to context.attributes for the List and Create controllers (you would never do ```GET /users/:id``` for instance)
* removal of a 404 status error when no results are found for list
* this could actually never have been triggered, and I would argue that if you find nothing you should always return status 200 with a [] result set
* otherwise code cleanup
=> 100% test coverage for epilogue

lib/Controllers/list.js, lib/Resource.js, lib/index.js, tests/resource/resource.test.js, tests/resource/sort.test.js
Adds customization of the sort parameter in a listing
```javascript
rest.resource({
model: test.models.User,
endpoints: ['/users', '/users/:id'],
sort: {
param: 'orderby',
attributes: ['username', 'createdAt']
}
});
```
param - choose the query parameter that is read for the sort, defaults to the existing 'sort'
attributes - list of fields that are allowed to be sorted on, defaults to all the raw attributes of the model
If a sorting attribute isn't included in the list of attributes (or in the raw attributes if the array isn't supplied) it will return a 400 bad request with an error message saying that sorting by the attribute is not allowed. This is a change from the current behaviour of waiting for the query to fail (for invalid columns) and returning an 500 internal server error.
=> Add customization for sort parameter

README.md, docs/Milestones.md, lib/Controllers/base.js, lib/Controllers/create.js, lib/Controllers/delete.js, lib/Controllers/list.js, lib/Controllers/read.js, lib/Controllers/update.js, lib/Errors.js, lib/index.js, package.json, tests/milestones/data/test-middleware-before-after.js, tests/milestones/data/test-middleware.js, tests/milestones/middleware.test.js, tests/milestones/milestones.test.js, tests/resource/resource.test.js
PR for #45 
Hook functions now return directly or a promise that resolves to `context.continue`, `context.skip`, `context.stop` to perform those actions.
Errors are no longer handled by setting context.error and passing it along the chain. Any errors thrown in the hook are caught (and stops execution of hooks) and rendered to the client. If it is a subclass of EpilogueError then it will render as the following JSON with the status code `err.status`. 
```
{
"message": err.message,
"errors": err.errors // is array
}
```
There are a few predefined errors in epilogue.Errors:
BadRequestError - forces HTTP 400
ForbiddenError - forces HTTP 403
NotFoundError - forces HTTP 404
RequestCompleted is a special case and causes no aditional rendering to the client and exits silently.
For situations were …
=> Use promises in hook system and change how errors are created

tests/resource/associations.test.js
The tests were actually starting before the `beforeEach` function was "finished". We just got lucky that the timing worked out.
=> Association test - finish beforeEach before starting test.

lib/associations/belongs-to-many.js, tests/associations/belongs-to-many.test.js
Do not throw an error if the paired association does not exist.
If only one belongsToMany association is existent, do not create the new resource because the paired association does not exist.
=> fix(association-belongsToMany)

lib/Resource.js, tests/resource/resource.test.js
With implementations dealing with associations under development, it would be a good idea to normalize the structure of `Resource.include`. This change forces includes to always be an array of objects that, at the very least, have a `model` property. This way we won't have to inspect includes all over the place.
This *may* break backwards compatibility if somebody is manipulating an include in their middleware and expects it to be just an array of models, although I haven't seen much evidence that anybody is doing this.
@mbroadst @Fridus
=> Force include to always have a model property

lib/Controllers/update.js, tests/resource/associations.test.js
This is an improvement over the other MR #67 
-  Controller `update` use the controller `read` to return data. (More logical)  
@mbroadst : Controller `read` and `list` are unmodified. They always returned the associated data if this is defined on resource.
- Allow change associated object based on nested identifier
- Reload the instance before send it if needed
- I think this is not a breaking change because the identifier is present like before this feature.
=> Update nested primkey

lib/Controllers/update.js, tests/resource/associations.test.js
Ex:  
`PUT` to `localhost:9000/tasks/4` :
```
{
"project": {"id": null }
}
```
or
```
{
"project": null
}
```
Result
```
{
"id": 4,
"title": "Task 4",
"description": "... 4",
"deadline": null,
"createdAt": "2015-06-09T13:22:16.761Z",
"updatedAt": "2015-06-09T13:22:19.142Z",
"projectId": null,
"project": null
}
```
=> Can set an associated object to null

README.md, lib/Controllers/list.js, tests/resource/search.test.js
This enables devs to specify a operator to use in conjunction with other search options. Check the readme changes for additional details and example usage.
=> Adds custom search operator 

README.md, lib/Controllers/list.js, tests/resource/sort.test.js
Adds default sort criteria, defined by the `default` attribute in `sort` options. 
```javascript
var users = rest.resource({
model: User,
endpoints: ['/users', '/users/:id'],
sort: {
default: '-email,username'
}
});
```
This makes...
```bash
$ curl http://localhost/users
```
...functionally equivalent to:
```bash
$ curl http://localhost/users?sort=-email,username
```
=> Adds default sort criteria

lib/Controllers/list.js, tests/resource/search.test.js
I noticed that if the search parameter is used on "list" routes in combination with field-specific filters (think: `GET /employees?gender=male&q=steve`, it errors out with:
```JSON
{
"message": "internal error",
"errors": [
"column Employee.args does not exist"
]
}
```
In this case, the `where` criteria isn't being built quite right in [list.js](https://github.com/dchester/epilogue/blob/master/lib/Controllers/list.js#L99). I've adjusted this and added a new test case.
=> fix(search): Fulltext search against filtered results

lib/Resource.js, lib/index.js, package.json
Removed merge-defaults as dependency.
[defaultsDeep](https://lodash.com/docs#defaultsDeep) also merges arrays, that's not desirable, so used defaults too.
Both methods mutates the object in 1st argument, no need to assign it to the variable.
=> Replace merge-defaults with lodash defaultsDeep

lib/Controllers/base.js, lib/Controllers/delete.js, lib/Controllers/list.js, lib/Controllers/read.js, tests/milestones/milestones.test.js
This patch adds access to the `context.options` object before the fetch milestone, which allows the user to pass in custom query options before the find query is executed.
This is useful for a variety of reasons, allowing users to alter base sequelize query options like `attributes` or `transaction` and `lock`, but will also allow for more flexible integration with custom sequelize addons that may add other custom query options.
Offering similar options for create/update/delete in the future would likely be a good idea, but this patch simply only adds it for the read/list actions.
=> Add support for altering base query options via context.options

lib/index.js, tests/epilogue.test.js
In reference to #119, I think I makes sense to check the validity of the Sequelize instance on runtime.
This tiny attribute checking isn't perfect, but it will avoid errors when an invalid sequelize instance is passed to epilogue.
=> check sequelize instance on runtime

lib/associations/belongs-to-many.js, lib/associations/has-many.js
Use association.target.primaryKeyField to set the name of the target primary key field rather than 'id'.
=> Fix hardcoded target primary key field name

lib/Resource.js
If the resource's `autoPopulate` option is explicitly set to `false`, it will not be added to the include list
=> Omit assocition, if autoPopulate is set to false

docs/Milestones.md
`contiue` → `continue`
`parmeter` → `parameter`
=> chore(docs): fix typos

README.md
As a completely new user (epilogue was mentioned in #express IRC channel and I looked it up) I found the code examples in the README very difficult to parse due to inconsistent variable naming.
* In the first example, `var epilogue` was used to reference the epilogue module, this then changed in later examples to `var rest`. Without providing context for what `rest` represents in the example, this is deeply confusing - especially since the variable does not exist in the keynote example.
* In the first example, `var userResource` is used to reference the created resource. In the next example `users` is used without any context.
* Use `var epilogue = require('epilogue');` everywhere, so in all examples, it is clear what the epilogue variable represents.
* Use `var users` in the …
=> Make variable names in README examples consistent

lib/Controllers/base.js, lib/associations/belongs-to-many.js, package.json, tests/resource/sort.test.js
Breaking changes from Lodash:
https://github.com/lodash/lodash/wiki/Changelog#v400
- Removed _.findWhere in favor of _.find with iteratee shorthand
- Absorbed _.sortByAll into _.sortBy
=> Upgrade lodash@4.8.2

package.json
The fix will make it work well in both win7 and linux system
=> Make "npm run coverage" work well in both windows 7 and linux.

lib/Controllers/create.js, lib/Controllers/update.js, tests/issues/117.test.js
Use `_.defaults` instead of `_.extend` inside `Update.write` and `Create.write` to enable modifying attributes in the `.write.before` - hook.
This should solve #117 ...
Any possible side-effects?
=> Switch to LoDash.defaults in create and update-controller

lib/Controllers/update.js, tests/resource/resource.test.js
**Added support of `excludeAttributes:[]` into `update` controller.**
I followed the same approach as  in `create` controller.
**Scenario to handle:**
When updating a user record that has a password we certainly do not want to see salt and password-hash in responses from server.
====================================
I suppose that's another hotfix before rethinking  this approach.
Thank you
=> Bug fix for update controller with excludeAttribute response

lib/Controllers/list.js
As we had discovered, there is a hard limit of 1000, overriding count parameter that is passed into the context.  I have removed it.
=> Remove hard limit of 1000 on query

lib/Controllers/read.js, tests/resource/resource.test.js
Needed a support for Sequelize scopes also in case of read operations.
May be useful in some cases - e.g. we have used it to steer what set of includes we get.
=> added support for scopes for 'read' endpoints
